import { Inter, Jost, Crimson_Text } from "next/font/google";
import { HeroUIProvider } from "@heroui/react";

import "./globals.css";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const crimson_text = Crimson_Text({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-crimson",
});

export const metadata = {
  title: "My Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jost.variable} ${crimson_text.variable} antialiased`}
      >
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
